export const RoasGraphData = [
  { name: '09', thisMonth: 0, lastMonth: 0.8 },
  { name: '10', thisMonth: 1.4, lastMonth: 1.1 },
  { name: '11', thisMonth: 1.8, lastMonth: 2.1 },
  { name: '12', thisMonth: 1.5, lastMonth: 2.5 },
  { name: '13', thisMonth: 2.0, lastMonth: 2.6 },
  { name: '14', thisMonth: 2.8, lastMonth: 3.1 },
  { name: '15', thisMonth: 3.2, lastMonth: 2.3 },
];

export const DCluttrData = [
  {
    source: 'Meta Ads',
    spends: '₹8,526.32',
    roas: 6.79,
    dcluttrRoas: 4.26,
    dcluttrPurchases: 45,
    dcluttrCV: '₹12,033.22',
    dcluttrSessions: '3.3%',
  },
  {
    source: 'Google Ads',
    spends: '₹8,526.32',
    roas: 4.98,
    dcluttrRoas: 2.79,
    dcluttrPurchases: 39,
    dcluttrCV: '₹12,033.22',
    dcluttrSessions: '18%',
  },
  {
    source: 'Store',
    spends: '',
    roas: '',
    dcluttrRoas: '',
    dcluttrPurchases: '',
    dcluttrCV: '',
    dcluttrSessions: '',
  },
  {
    source: 'Web Analytics',
    spends: '',
    roas: '',
    dcluttrRoas: '',
    dcluttrPurchases: '',
    dcluttrCV: '',
    dcluttrSessions: '',
  },
  {
    source: 'Total (for 09 sources)',
    spends: '₹93,132.12',
    roas: 4.52,
    dcluttrRoas: 4.52,
    dcluttrPurchases: 1251,
    dcluttrCV: '₹12,033.22',
    dcluttrSessions: '1.52',
    type: 'total',
  },
];
